name = "hapi-phillipclapham"
main = "workers/hapi-generated.js"
compatibility_date = "2024-01-01"

# After creating KV namespace, uncomment and add your ID:
# [[kv_namespaces]]
# binding = "HAPI_KV"
# id = "YOUR_KV_NAMESPACE_ID_HERE"

# You'll set this in dashboard
# [vars]
# INBOX_SECRET = "your-secret-here"
