name = "hapi-phillipclapham"
main = "workers/hapi-generated.js"
compatibility_date = "2024-01-01"

# You'll create this KV namespace in Cloudflare dashboard
# [[kv_namespaces]]
# binding = "HAPI_KV"
# id = "YOUR_KV_ID_HERE"

# Environment variables (set in Cloudflare dashboard)
# [vars]
# INBOX_SECRET = "set-in-dashboard"
